LeaveApiKlient/Models/Employee.cs
using System.ComponentModel.DataAnnotations;

namespace LeaveApiClient.Models
{
    public class Employee
    {
        [Key]
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string Email { get; set; }
    }
}

LeaveApiKlient/Models/ErrorViewModel.cs
namespace LeaveApiKlient.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LeaveApiKlient/Models/Leave.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LeaveApiClient.Models
{
    public enum LeaveStatus
    {
        //0,1,2
        Pending, Approved, Denied
    }
    public enum LeaveType
    {
        //0,1,2,3
        Holliday,
        Sick,
        Peronal,
        Other
    }
    public class Leave
    {
        [Key]
        public int LeaveId { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public LeaveType Type { get; set; }
        public LeaveStatus Status { get; set; } = LeaveStatus.Pending;
        [ForeignKey("Employee")]
        public int FkEmployeeId { get; set; }
        public Employee? Employee { get; set; }
    }
}

LeaveApiKlient/Controllers/EmployeesController.cs
using LeaveApiClient.Models;
using LeaveApiClient.Services;
using Microsoft.AspNetCore.Mvc;

namespace LeaveApiClient.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly ApiService _apiService;
        public EmployeesController(ApiService apiService)
        {
            _apiService = apiService;
        }
        public async Task<IActionResult> Index()
        {
            var employees = await _apiService.GetEmployeesAsync();
            if (employees == null || !employees.Any())
            {
                return View(new List<Employee>());
            }

            return View(employees);
        }
        // Get: Employees/create
        public IActionResult Create()
        {
            return View();
        }
        // Post: Emploees/create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Employee employee)
        {
            if (ModelState.IsValid)
            {
                await _apiService.AddEmployeeAsync(employee);
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }
        // Show a form to get an employee
        ////// GET: Employees/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var employee = await _apiService.GetEmployeeByIdAsync(id);
            return View(employee);
        }
        ////// Uppdate an employee
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Employee employee)
        {
            if (ModelState.IsValid)
            {
                await _apiService.UpdateEmployeeAsync(id, employee);
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }
        // Get details for employees
        public async Task<IActionResult> Details(int id)
        {
            var employee = await _apiService.GetEmployeeByIdAsync(id);
            return View(employee);
        }

        //[HttpGet]
        //public async Task<IActionResult> Delete(int id)
        //{
        //    var employee = await _apiService.GetEmployeeByIdAsync(id);
        //    if (employee == null)
        //        return NotFound();
        //    return View(employee);
        //}
        [HttpPost, ActionName("DeleteConfirmed")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _apiService.DeleteEmployeeAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

LeaveApiKlient/Controllers/HomeController.cs
using LeaveApiKlient.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace LeaveApiKlient.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LeaveApiKlient/Controllers/LeavesController.cs
using LeaveApiClient.Models;
using LeaveApiClient.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LeaveApiClient.Controllers
{
    public class LeavesController : Controller
    {
        private readonly ApiService _apiService;
        public LeavesController(ApiService apiService)
        {
            _apiService = apiService;
        }
        public async Task<IActionResult> Index()
        {
            var leaves = await _apiService.GetAllLeavesAsync();
            if (leaves == null || !leaves.Any())
            {
                return View(new List<Leave>());
            }

            return View(leaves);
        }
        // Get: Leave/create hämtar f rtt tomt formulär
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var employees = await _apiService.GetEmployeesAsync();
            if (!employees.Any())
            {
                employees = new List<Employee>();
            }
            ViewBag.Employees = new SelectList(employees, "EmployeeId", "EmployeeName");
            ViewBag.LeaveTypes = new SelectList(Enum.GetValues(typeof(LeaveType))
                .Cast<LeaveType>()
                .Select(x => new { Id = (int)x, Name = x.ToString() }),
                "Id", "Name");
            return View();
        }
        // Post: Leaves/create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Leave leave)
        {
            if (!ModelState.IsValid)
            {
                return View(leave);
            }
            await _apiService.AddLeaveAsync(leave);

            return View(leave);
        }
        // hämta detaljer för en view
        public async Task<IActionResult> Details(int id)
        {
            var leave = await _apiService.GetLeaveByIdAsync(id);
            if (leave == null)
            {
                return NotFound();
            }
            return View(leave);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var leave = await _apiService.GetLeaveByIdAsync(id);
            if (leave == null)
                return NotFound();

            var employees = await _apiService.GetEmployeesAsync();
            if (employees == null || !employees.Any())
            {
                // Log the error or handle the situation appropriately
                employees = new List<Employee>(); // Ensure it's never null to avoid SelectList issues
            }

            ViewBag.Employees = new SelectList(employees, "EmployeeId", "EmployeeName", leave.FkEmployeeId);
            return View(leave);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Leave leave)
        {
            if (id != leave.LeaveId)
                return NotFound();

            if (ModelState.IsValid)
            {
                await _apiService.UpdateLeaveAsync(id, leave);
                return RedirectToAction(nameof(Index));
            }
            return View(leave);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var leave = await _apiService.GetLeaveByIdAsync(id);
            if (leave == null)
                return NotFound();

            return View(leave);
        }

        [HttpPost, ActionName("DeleteConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _apiService.DeleteLeaveAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

LeaveApiKlient/Views/Employees/Create.cshtml
@model LeaveApiClient.Models.Employee
<h2>Add employee</h2>
<form asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="EmployeeName" class="control-label"/>
        <input asp-for="EmployeeName" class="form-control"/>
        <span asp-validation-for="EmployeeName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label" />
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type ="submit" value="Create" class="btn-outline-primary"/>
    </div>
</form>

LeaveApiKlient/Views/Employees/Delete.cshtml
@model LeaveApiClient.Models.Employee
<h2>Delete employees</h2>
<h3>Are you sure you want to delete this employee</h3>
<div>
    <h4>Employee</h4>
    <hr/>
    <dl class="dl-horizontal">
        <dt>Name</dt>
        <dd>@Model.EmployeeName</dd>
        <dt>Email</dt>
        <dd>@Model.Email</dd>
    </dl>
    <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="EmployeeId"/>
        <input type="submit" value="Delete" class="btn btn-danger"/>
        <a asp-action="Index" class="btn btn-success">Cancel</a>
    </form>
</div>

LeaveApiKlient/Views/Employees/Details.cshtml
@model LeaveApiClient.Models.Employee
<h2>Employee details</h2>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            ID
        </dt>
        <dd class="col-sm-10">
            @Model.EmployeeId
        </dd>
        <dt class="col-sm-2">
            Name
        </dt>
        <dd class="col-sm-10">
            @Model.EmployeeName
        </dd>
        <dt class="col-sm-2">
            Email
        </dt>
        <dd class="col-sm-10">
            @Model.Email
        </dd>
    </dl>
    <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model.EmployeeId">Edit</a>
    <a asp-action="Index" class="btn btn-success">Back to list</a>
</div>

LeaveApiKlient/Views/Employees/Edit.cshtml
@model LeaveApiClient.Models.Employee

<h2>Edit Employees</h2>
<form asp-action="Edit" method="post">
    <input type="hidden" asp-for="EmployeeId"/>
    <div class="form-group">
        <label asp-for="EmployeeName" class="control-label"></label>
        <input asp-for="EmployeeName" class="form-control"/>
        <span asp-validation-for="EmployeeName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="save" class="btn btn-warning"/>
    </div>
</form>

LeaveApiKlient/Views/Employees/Index.cshtml
@using LeaveApiClient.Models
@model List<Employee>
<h1>Employees</h1>
<a asp-action="Create" class="btn btn-primary">Add a new employee</a>
@if(Model.Any())
{
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Actions</th>
        </tr>
        @foreach(var employee in Model)
        {
            <tr>
                <td>@employee.EmployeeName</td>
                <td>@employee.Email</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@employee.EmployeeId" class="btn btn-primary">Edit</a>
                    <a asp-action="Details" asp-route-id="@employee.EmployeeId" class="btn btn-primary">Details</a>
                    @* <a asp-action="Delete" asp-route-id="@employee.EmployeeId" method="post" class="btn btn-danger">Delete</a> *@
                    <form asp-action="DeleteConfirmed" class="d-inline-block" asp-route-id="@employee.EmployeeId" method="post">
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this employee?');">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </table>
}
else
{
    <p>No employees in the database</p>
}

LeaveApiKlient/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

LeaveApiKlient/Views/Leaves/Create.cshtml
@using LeaveApiClient.Models
@model LeaveApiClient.Models.Leave
<h2>Create new Leave</h2>
<form asp-action="Create" method="post">
    <div class="form-group">
        <label asp-for="FkEmployeeId">Employee</label>
        <select asp-for="FkEmployeeId" asp-items="ViewBag.Employees" class="form-control"></select>
        <span asp-validation-for="FkEmployeeId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="StartDate" class="control-label" ></label>
        <input asp-for="StartDate" class="form-control" />
        <span asp-validation-for="StartDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="EndDate" class="control-label" ></label>
        <input asp-for="EndDate" class="form-control" />
        <span asp-validation-for="EndDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Type" class="control-label" />
        <select asp-for="Type" asp-items="ViewBag.LeaveTypes" class="form-control"></select>
        <span asp-validation-for="Type" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Status" class="control-label" />
        <select asp-for="Status" asp-items="Html.GetEnumSelectList<LeaveStatus>()" class="form-control"></select>
        <span asp-validation-for="Status" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn-outline-primary" />
    </div>
</form>

LeaveApiKlient/Views/Leaves/Delete.cshtml
@model LeaveApiClient.Models.Leave
<h2>Delete employees</h2>
<h3>Are you sure you want to delete this Leave</h3>
<div>
    <h4>Employee</h4>
    <hr />
@*     <dl class="dl-horizontal">
        <dt>Name</dt>
        <dd>@Model.EmployeeName</dd>
        <dt>Email</dt>
        <dd>@Model.Email</dd> *@
    </dl>
@*     <form asp-action="Delete" method="post">
        <input type="hidden" asp-for="EmployeeId" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-success">Cancel</a>
    </form> *@
</div>

LeaveApiKlient/Views/Leaves/Details.cshtml
@model LeaveApiClient.Models.Leave

@{
    ViewData["Title"] = "Leave Details";
}

<h1>Leave Details</h1>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Leave ID: @Model.LeaveId</h4>
        <p class="card-text">Employee ID: @Model.FkEmployeeId</p>
        <p class="card-text">Start Date: @Model.StartDate.ToString("yyyy-MM-dd")</p>
        <p class="card-text">End Date: @Model.EndDate.ToString("yyyy-MM-dd")</p>
        <p class="card-text">Leave Type: @Model.Type</p>
        <p class="card-text">Status: @Model.Status</p>

        <a asp-action="Edit" asp-route-id="@Model.LeaveId" class="btn btn-primary">Edit</a>
        <a asp-action="Delete" asp-route-id="@Model.LeaveId" class="btn btn-danger">Delete</a>
        <a asp-action="Index" class="btn btn-secondary">Back to List</a>
    </div>
</div>

LeaveApiKlient/Views/Leaves/Edit.cshtml
@model LeaveApiClient.Models.Leave

@{
    ViewData["Title"] = "Edit Leave";
}

<h1>Edit Leave</h1>

<form asp-action="Edit" asp-controller="Leaves" method="post">
    <input type="hidden" asp-for="LeaveId" />
    <div class="form-group">
        <label asp-for="StartDate" class="control-label"></label>
        <input asp-for="StartDate" class="form-control" type="date" />
        <span asp-validation-for="StartDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="EndDate" class="control-label"></label>
        <input asp-for="EndDate" class="form-control" type="date" />
        <span asp-validation-for="EndDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Type" class="control-label"></label>
        <select asp-for="Type" class="form-control" asp-items="Html.GetEnumSelectList<LeaveApiClient.Models.LeaveType>()">
            <option>Please select one</option>
        </select>
        <span asp-validation-for="Type" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Status" class="control-label"></label>
        <select asp-for="Status" class="form-control" asp-items="Html.GetEnumSelectList<LeaveApiClient.Models.LeaveStatus>()">
            <option>Please select one</option>
        </select>
        <span asp-validation-for="Status" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="FkEmployeeId" class="control-label">Employee</label>
        <select asp-for="FkEmployeeId" class="form-control" asp-items="ViewBag.Employees"></select>
        <span asp-validation-for="FkEmployeeId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

LeaveApiKlient/Views/Leaves/Index.cshtml
@using LeaveApiClient.Models
@model IEnumerable<Leave>
<h1>All leaves</h1>
<a asp-action="Create" class="btn btn-primary">Add a new leave</a>
@if (Model.Any())
{
    <table class="table">
        <tr>
            <th>Id</th>
            <th>Employee</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Status</th>
            <th></th>
        </tr>
        @foreach (var leave in Model)
        {
            <tr>
                <td>@leave.LeaveId</td>
                <td>@leave.Employee.EmployeeName</td>
                <td>@leave.StartDate.ToString("yyyy-MM-dd")</td>
                <td>@leave.EndDate.ToString("yyyy-MM-dd")</td>
                <td>@leave.Status</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@leave.LeaveId" class="btn btn-primary">Edit</a>
                    <a asp-action="Details" asp-route-id="@leave.LeaveId" class="btn btn-primary">Details</a>
                    @* <a asp-action="Delete" asp-route-id="@employee.EmployeeId" method="post" class="btn btn-danger">Delete</a> *@
                    <form asp-action="DeleteConfirmed" class="d-inline-block" asp-route-id="@leave.LeaveId" method="post">
                        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this leave?');">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </table>
}
else
{
    <p>No employees in the database</p>
}

LeaveApiKlient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LeaveApiKlient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LeaveApiKlient.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LeaveApiKlient</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">All empoyees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Leaves" asp-action="Index">All leaves</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LeaveApiKlient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>